CREATE DATABASE IF NOT EXISTS `my_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `my_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'phpmyadmin_user'@'%' IDENTIFIED BY 'secret!';
GRANT ALL PRIVILEGES ON *.* TO 'phpmyadmin_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
